config-version: 1

client-id: ""
bot-token: ""
invite-link: "00000000000"
avatar-url: "https://crafthead.net/avatar/{0}/{1}"
dodo:
  island-id: ""
  chat-channel: "1995351"

database:
  mysql: false
  host: localhost
  port: 3306
  database: dodosrv
  user: root
  password: passwd
  prefix: "dodosrv_"
  usessl: false
  properties:
    connection-timeout: 60000
    validation-timeout: 3000
    idle-timeout: 60000
    login-timeout: 10
    maxLifeTime: 60000
    maximum-pool-size: 8
    minimum-idle: 2
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useUnicode: true
    characterEncoding: utf8
    allowPublicKeyRetrieval: true
feature:
  minecraft-to-dodo:
    enable: true
    chat-truncate-length: 256
    translate-mentions: true
    require-prefix: ""
    forward:
      chat: true
      join: true
      quit: true
      death: true
      advancement: true
  dodo-to-minecraft:
    enable: true
    translate-mentions: true
    ignore-users: [ ]
    require-prefix: ""